#!/bin/sh /etc/rc.common

START=19

start()
{
    echo -n Starting ip6tables
    ip6tables-restore < /etc/ip6tables.save
    if [ $? == 0 ] ; then
	echo -e "\t[ OK ]"
    else
	echo -e "\t[FAIL]"
    fi
}

stop()
{
    echo -n Stopping ip6tables
    ip6tables-save | \
	sed -rn '/^(\*|:|COMMIT)/ { s/\[[^]]+\]//; s/DROP/ACCEPT/; p }' | \
	ip6tables-restore
    if [ $? == 0 ] ; then
	echo -e "\t[ OK ]"
    else
	echo -e "\t[FAIL]"
    fi
}

case $1 in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	start
	;;
esac
