#!/bin/sh /etc/rc.common

START=18

start()
{
    echo -n Starting ipset
    ipset restore < /etc/ipset.save
    if [ $? == 0 ] ; then
	echo -e "\t[ OK ]"
    else
	echo -e "\t[FAIL]"
    fi
}

stop()
{
    echo -n Stopping ipset
    awk '$1 == "-N"  ||
	 $1 == "new" ||
	 $1 == "create" { printf("-F %s\n", $2) }' /etc/ipset.save | \
	ipset restore
    if [ $? == 0 ] ; then
	echo -e "\t[ OK ]"
    else
	echo -e "\t[FAIL]"
    fi
}

case $1 in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	start
	;;
esac
