#!/bin/sh /etc/rc.common

START=19

start()
{
    echo -n Starting iptables
    iptables-restore < /etc/iptables.save
    if [ $? == 0 ] ; then
	echo -e "\t[ OK ]"
    else
	echo -e "\t[FAIL]"
    fi
}

stop()
{
    echo -n Stopping iptables
    iptables-save | \
	sed -rn '/^(\*|:|COMMIT)/ { s/\[[^]]+\]//; s/DROP/ACCEPT/; p }' | \
	iptables-restore
    if [ $? == 0 ] ; then
	echo -e "\t[ OK ]"
    else
	echo -e "\t[FAIL]"
    fi
}

case $1 in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	start
	;;
esac
